# Generated by Django 5.2.16 on 2026-08-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_temporary_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='temp_password_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
