"""
users/serializers.py

Serializers for Employee CRUD, invite, login, and status operations.
"""

from rest_framework import serializers
from .models import Employee


class EmployeeListSerializer(serializers.ModelSerializer):
    """
    Serializes employee data for the User Management table.
    Includes status (Active/Inactive), is_online (Online/Offline), and timestamps.
    """
    created_at = serializers.SerializerMethodField()
    last_login = serializers.SerializerMethodField()

    class Meta:
        model = Employee
        fields = [
            'id',
            'employee_id',
            'name',
            'company_email',
            'role',
            'status',
            'is_online',
            'last_login',
            'invite_sent',
            'created_at',
        ]

    def get_created_at(self, obj):
        if not obj.created_at:
            return ''
        return obj.created_at.strftime('%d %B %Y').lstrip('0')

    def get_last_login(self, obj):
        if not obj.last_login:
            return 'Never'
        return obj.last_login.strftime('%d %b %Y, %I:%M %p').lstrip('0')


class EmployeeInviteSerializer(serializers.Serializer):
    """
    Validates the Add User form input from the frontend.
    Requires: name, email, role.
    Initial password is auto-generated by the backend.
    """
    name = serializers.CharField(
        max_length=150,
        required=True,
        error_messages={
            'required': 'Full name is required.',
            'blank': 'Full name cannot be empty.',
        }
    )
    email = serializers.EmailField(
        required=False,
        error_messages={
            'invalid': 'Enter a valid email address.',
        }
    )
    personal_email = serializers.EmailField(
        required=False,
    )
    role = serializers.ChoiceField(
        choices=['Developer', 'Tester'],
        default='Developer',
        required=False,
    )

    def validate_name(self, value):
        if len(value.strip()) < 2:
            raise serializers.ValidationError('Full name must be at least 2 characters.')
        return value.strip()

    def validate(self, data):
        email_val = data.get('email') or data.get('personal_email')
        if not email_val or not email_val.strip():
            raise serializers.ValidationError({'email': 'Email is required.'})
        
        email_clean = email_val.strip().lower()
        if Employee.objects.filter(company_email=email_clean).exists():
            raise serializers.ValidationError({'email': 'An employee with this email already exists.'})
        
        data['email'] = email_clean
        return data


class EmployeeUpdateSerializer(serializers.ModelSerializer):
    """
    Serializer for updating employee profile details from the admin UI.
    """
    email = serializers.EmailField(required=False)
    password = serializers.CharField(write_only=True, required=False, allow_blank=True)

    class Meta:
        model = Employee
        fields = ['name', 'email', 'role', 'status', 'password']

    def validate_name(self, value):
        if len(value.strip()) < 2:
            raise serializers.ValidationError('Full name must be at least 2 characters.')
        return value.strip()

    def validate_email(self, value):
        email = value.strip().lower()
        if self.instance and self.instance.company_email == email:
            return email
        if Employee.objects.filter(company_email=email).exists():
            raise serializers.ValidationError('An employee with this email already exists.')
        return email

    def update(self, instance, validated_data):
        password = validated_data.pop('password', None)
        email = validated_data.pop('email', None)
        if password:
            from django.contrib.auth.hashers import make_password
            instance.company_password_hash = make_password(password)
        if email:
            instance.company_email = email
            
        return super().update(instance, validated_data)


class EmployeeLoginSerializer(serializers.Serializer):
    """
    Serializer for Employee login using company_email + password.
    """
    email = serializers.EmailField(required=True)
    password = serializers.CharField(required=True, write_only=True)
