# Generated by Django 5.2.16 on 2026-08-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bug_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('bug_type', models.CharField(max_length=30)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('dev_status', models.CharField(blank=True, default='In Progress', max_length=50)),
                ('module', models.CharField(max_length=200)),
                ('steps_text', models.TextField(blank=True)),
                ('files', models.JSONField(blank=True, default=list, null=True)),
                ('tester_email', models.EmailField(max_length=254)),
                ('tester_name', models.CharField(max_length=150)),
                ('tester_id', models.CharField(blank=True, max_length=50, verbose_name='Tester Employee ID')),
                ('developer_name', models.CharField(default='Unassigned', max_length=150)),
                ('developer_id', models.CharField(blank=True, max_length=50, verbose_name='Developer Employee ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tester_edited', models.BooleanField(default=False)),
                ('dev_resolved', models.BooleanField(default=False)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bug Report',
                'verbose_name_plural': 'Bug Reports',
                'db_table': 'bugs_bugreport',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('developer_name', models.CharField(max_length=150)),
                ('developer_id', models.CharField(blank=True, max_length=50, verbose_name='Developer Employee ID')),
                ('version', models.CharField(blank=True, default='v0.1', max_length=50, verbose_name='Build Version')),
                ('subject', models.CharField(max_length=300)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('project_link', models.CharField(blank=True, max_length=500, verbose_name='Project Link / URL')),
                ('status', models.CharField(default='Unread', max_length=20)),
                ('downloaded', models.BooleanField(default=False)),
                ('claimed_by', models.CharField(blank=True, max_length=150)),
                ('claimed_by_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'db_table': 'bugs_projectsubmission',
            },
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('sender_id', models.CharField(max_length=50, verbose_name='Sender ID')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('assigned_tester', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testing',
                'verbose_name_plural': 'Testings',
                'db_table': 'bugs_testing',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_role', models.CharField(max_length=20)),
                ('recipient_id', models.CharField(blank=True, max_length=50, verbose_name='Recipient Employee ID')),
                ('notification_type', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.CharField(blank=True, max_length=200, verbose_name='Project Name')),
                ('sender_id', models.CharField(blank=True, max_length=50, verbose_name='Sender ID')),
                ('bug_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bugs.bugreport')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'bugs_notification',
            },
        ),
    ]
