# Generated by Django 5.2.16 on 2026-08-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Employee ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('company_email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Company Email')),
                ('company_password_hash', models.CharField(max_length=255, verbose_name='Company Password (hashed)')),
                ('role', models.CharField(choices=[('Developer', 'Developer'), ('Tester', 'Tester')], default='Developer', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Inactive', max_length=20, verbose_name='Account Status')),
                ('is_online', models.BooleanField(default=False, verbose_name='Is Online')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('invite_sent', models.BooleanField(default=False, verbose_name='Invite Email Sent')),
                ('is_temporary_password', models.BooleanField(default=False, verbose_name='Is Temporary Password')),
                ('temp_password_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Temporary Password Expiry')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
