# Generated by Django 5.2.16 on 2026-08-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='personal_email',
        ),
    ]
