# Generated by Django 4.2.30 on 2026-09-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Tester', 'Tester'), ('CTO', 'CTO'), ('Designer', 'Designer')], default='Developer', max_length=20),
        ),
    ]
